# docker-compose.yml
services:
  ki_pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ki_pipeline
    # GPU aktivieren (Host braucht NVIDIA Treiber + nvidia-container-toolkit)
    deploy: {}
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      # Live-Entwicklung: mount lokale Ordner, falls du nicht im Image arbeiten willst
      - ./src:/app/src
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "6006:6006"  # TensorBoard
      - "8501:8501"  # Streamlit UI
    shm_size: "8g"
    working_dir: /app/src
    command: python training.py
