best_val_loss: 212.3201560974121
config:
  augmentation_file: augmentation_1
  batch_size: 16
  dataset_root: datasets/object_detection/Type_COCO/Test_Duckiebots/
  dataset_type: Type_COCO
  early_stopping: 10
  epochs: 5
  learning_rate: 0.001
  model_file: cnn_001
  model_type_file: object_detection
experiment_name: 20250807_112106_cnn_001
model_architecture: cnn_001
test_loss: 270.45263671875
timestamp: '20250807_112106'
total_epochs: 5
