# Training parameters
epochs: 5
batch_size: 16
learning_rate: 0.001
early_stopping: 10

# Augmentation
augmentation_file: "augmentation_1"  # Name des Augmentierungs-Files

# Model
model_type_file: "object_detection"  # Neu hinzufügen
model_file: "cnn_001"  # Name des Model-Files


# Dataset
dataset_root: "datasets/object_detection/Type_YOLO/Test_Duckiebots_YOLO11/"
dataset_type: "Type_YOLO"  # Typ des Datasets
#annotation_file: "datasets/object_detection/Type_COCO/Test_Duckiebots/annotations/instances_train.json"