# Training parameters
epochs: 5
batch_size: 16
learning_rate: 0.001
early_stopping: 10

# dropout rate
# seed (f端r zufallsprozesse zentral)
#scheduler: (evtl weight decay)
#optimizer: (adam, sgd, ...)
# hydra f端r yaml

#logger hinzuf端gen (loguru)

#ImageNet classifizierung
#pytorch timm hat pretrained transformer

# Augmentation
augmentation_file: "augmentation_1"  # Name des Augmentierungs-Files

# Model
model_type_file: "object_detection"  # Neu hinzuf端gen
model_file: "ResNet50"  # Name des Model-Files


# Dataset
dataset_root: "datasets/object_detection/Type_COCO/Test_Duckiebots/"
dataset_type: "Type_COCO"  # Typ des Datasets
#annotation_file: "datasets/object_detection/Type_COCO/Test_Duckiebots/annotations/instances_train.json"