# Training parameters
epochs: 100
batch_size: 16
learning_rate: 0.001
early_stopping: 10

# Augmentation
augmentation_file: "augmentation_1"  # Name des Augmentierungs-Files

# Model
model_type: "object_detection"
model_name: "cnn_001"


# Dataset
dataset_root: "datasets/object_detection/Type_COCO/Duckiebots/"
annotation_file: "datasets/object_detection/Type_COCO/Duckiebots/annotations/instances_train.json"