# Training parameters
epochs: 5
batch_size: 16
learning_rate: 0.001
early_stopping: 10

# Scheduler parameters
scheduler_file: "scheduler"
scheduler_type: "ReduceLROnPlateau"  # StepLR, MultiStepLR, ExponentialLR, CosineAnnealingLR, ReduceLROnPlateau
scheduler_patience: 5  # Für ReduceLROnPlateau
scheduler_factor: 0.5  # Faktor um den LR reduziert wird
scheduler_min_lr: 1e-6  # Minimum learning rate

# Optimizer parameters
optimizer_type: "AdamW"  # Adam, AdamW, SGD, RMSprop, Adagrad, Adadelta
optimizer_weight_decay: 0.01  # L2 regularization
optimizer_betas: [0.9, 0.999]  # Für Adam/AdamW
optimizer_momentum: 0.9  # Für SGD


# dropout rate
seed: 1234


# hydra für yaml
#logger hinzufügen (loguru)

#ImageNet classifizierung
#pytorch timm hat pretrained transformer

# Augmentation
augmentation_file: "augmentation_1"  # Name des Augmentierungs-Files

# Model
model_type_file: "object_detection"  # Neu hinzufügen
model_file: "swin_tiny_patch4_window7_224"  # Name des Model-Files


# Dataset
dataset_root: "datasets/object_detection/Type_COCO/Test_Duckiebots/"
dataset_type: "Type_COCO"  # Typ des Datasets



# Transfer Learning Configuration
transfer_learning:
  enabled: false  # Ob Transfer Learning verwendet werden soll
  pretrained_model_path: "trained_models/object_detection/20250808_095238_ResNet50/models/best_model.pth"
  base_model_type: "object_detection"  # Typ des Base Models
  base_model_file: "ResNet50"  # Name des Base Model Files
  
  # Transfer Learning Strategy
  strategy: "freeze_all_except_head"  # freeze_all_except_head, freeze_early_layers, freeze_backbone, unfreeze_all, custom_freeze
  
  # Für freeze_early_layers Strategy
  freeze_until_layer: 6
  
  # Für custom_freeze Strategy
  freeze_layers: ["backbone.layer1", "backbone.layer2"]
  unfreeze_layers: ["detection_head", "backbone.layer4"]
  
  # Learning Rate für verschiedene Teile
  backbone_lr_multiplier: 0.1  # Kleinere LR für Backbone
  head_lr_multiplier: 1.0      # Normale LR für Head

# Model Configuration - wird überschrieben wenn Transfer Learning enabled
trans_model_type_file: "object_detection"
trans_model_file: "transferlearning"  # Verwendet Transfer Learning Wrapper