# Training parameters
epochs: 5
batch_size: 16
learning_rate: 0.001
early_stopping: 10

# Scheduler parameters
scheduler_file: "scheduler"
scheduler_type: "ReduceLROnPlateau"  # StepLR, MultiStepLR, ExponentialLR, CosineAnnealingLR, ReduceLROnPlateau
scheduler_patience: 5  # Für ReduceLROnPlateau
scheduler_factor: 0.5  # Faktor um den LR reduziert wird
scheduler_min_lr: 1e-6  # Minimum learning rate

# Optimizer parameters
optimizer_type: "AdamW"  # Adam, AdamW, SGD, RMSprop, Adagrad, Adadelta
optimizer_weight_decay: 0.01  # L2 regularization
optimizer_betas: [0.9, 0.999]  # Für Adam/AdamW
optimizer_momentum: 0.9  # Für SGD


# dropout rate
seed: 1234


# hydra für yaml
#logger hinzufügen (loguru)

#ImageNet classifizierung
#pytorch timm hat pretrained transformer

# Augmentation
augmentation_file: "augmentation_1"  # Name des Augmentierungs-Files

# Model
model_type_file: "object_detection"  # Neu hinzufügen
model_file: "ResNet50"  # Name des Model-Files


# Dataset
dataset_root: "datasets/object_detection/Type_COCO/Test_Duckiebots/"
dataset_type: "Type_COCO"  # Typ des Datasets
#annotation_file: "datasets/object_detection/Type_COCO/Test_Duckiebots/annotations/instances_train.json"