training:
  epochs: 3
  batch_size: 16
  learning_rate: 0.001
  early_stopping_patience: 10
  random_seed: 42

scheduler:
  file: "scheduler"
  type: "CosineAnnealingLR" # StepLR, MultiStepLR, ExponentialLR, CosineAnnealingLR, ReduceLROnPlateau
  patience: 5
  factor: 0.5
  min_lr: 1e-6

optimizer:
  type: "AdamW" # Adam, AdamW, SGD, RMSprop, Adagrad, Adadelta
  weight_decay: 0.01
  adam:
    betas: [0.9, 0.999]
  sgd:
    momentum: 0.9

augmentation:
  file: "augmentation_1"

model:
  type: "object_detection"
  file: ""
  transfer_learning:
    enabled: true      #             !!!IMMER true/false WICHTIG!!!
    path: "trained_models/object_detection/20250814_145642_cnn_001/models/best_model_weights.pth"
    trans_file: "transferlearning"
    freezing:
      enabled: true
      strategy: "freeze_all_except_head" # freeze_all_except_head, freeze_early_layers, freeze_backbone, unfreeze_all, custom_freeze
      freeze_early_layers:
        freeze_until_layer: 6
      custom:
        freeze_layers: ["backbone.layer1", "backbone.layer2"]
        unfreeze_layers: ["detection_head", "backbone.layer4"]
    lr:
      backbone_lr_multiplier: 0.1
      head_lr_multiplier: 1.0

dataset:
  root: "datasets/object_detection/Type_COCO/Test_Duckiebots/"
  type: "Type_COCO"
  num_classes: 4
