training:
  epochs: 5
  batch_size: 16
  learning_rate: 0.001
  early_stopping_patience: 10
  random_seed: 42
  debug_mode: false
scheduler:
  file: "scheduler"
  type: "StepLR"
  step_size: 10
  gamma: 0.1
  milestones: [30, 60, 90]
  T_max: 50
  eta_min: 1e-06
  mode: "min"
  factor: 0.5
  patience: 5
  threshold: 0.0001
  cooldown: 0
  min_lr: 1e-06
optimizer:
  type: "Adam"
  weight_decay: 0.01
  adam:
    betas: [0.9, 0.999]
  sgd:
    momentum: 0.9
augmentation:
  file: "augment_rotate_flip_shear_translate_brightness"
model:
  type: "object_detection"
  file: "FastRCNN_001"
  transfer_learning:
    enabled: false
    path: ''
    trans_file: "transferlearning"
    head_name: "detection_head"
    backbone_name: "backbone"
    freezing:
      enabled: false
      strategy: "freeze_all_except_head"
      freeze_early_layers:
        freeze_until_layer: 6
      custom:
        freeze_layers: ["backbone.layer1", "backbone.layer2"]
        unfreeze_layers: ["detection_head", "backbone.layer4"]
    lr:
      backbone_lr_multiplier: 0.1
      head_lr_multiplier: 1.0
dataset:
  root: "datasets/object_detection/Type_COCO/Duckiebots_mini/"
  type: "Type_COCO"
  num_classes: 4
  autosplit:
    enabled: false
    train_ratio: 0.7
    val_ratio: 0.15
    test_ratio: 0.15
